name: Setup Wrapper

on:
  push:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Gradle 8.5
        run: |
          wget https://services.gradle.org/distributions/gradle-8.5-bin.zip
          unzip gradle-8.5-bin.zip
          sudo mv gradle-8.5 /opt/gradle
          export PATH=$PATH:/opt/gradle/bin
          gradle -v

      - name: Generate Wrapper
        run: |
          export PATH=$PATH:/opt/gradle/bin
          gradle wrapper --gradle-version 8.5

      - name: Commit Wrapper
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Add Gradle Wrapper"
          git push
